// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EventsEmit(arg1:string,arg2:Array<any>):Promise<void>;

export function EventsOff(arg1:string):Promise<void>;

export function EventsOnMultiple(arg1:string,arg2:number):Promise<void>;

export function EventsOnStart(arg1:string):Promise<void>;

export function EventsOnce(arg1:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;
