// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EventsEmit(arg1, arg2) {
  return window['go']['main']['App']['EventsEmit'](arg1, arg2);
}

export function EventsOff(arg1) {
  return window['go']['main']['App']['EventsOff'](arg1);
}

export function EventsOnMultiple(arg1, arg2) {
  return window['go']['main']['App']['EventsOnMultiple'](arg1, arg2);
}

export function EventsOnStart(arg1) {
  return window['go']['main']['App']['EventsOnStart'](arg1);
}

export function EventsOnce(arg1) {
  return window['go']['main']['App']['EventsOnce'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
